name: CI Pipeline

on:
    push:
        branches:
            - master
jobs: # series of steps run on trigger
    build:
        runs-on: ubuntu-latest # OS avail on Github actions
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3 
            - name: Secret Scanning
              uses: trufflesecurity/trufflehog@main
              with:
                extra_args: --results=verified,unknown
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18.x' 
                cache: 'npm'

            - name: Start MongoDB # Setup mongodb in CI env - integration tests
            # Guide: https://github.com/marketplace/actions/mongodb-in-github-actions
              uses: supercharge/mongodb-github-action@1.9.0  
              with:
                mongodb-version: '6.0'

            - name: Install dependencies
              run: npm ci

            - name: Run Tests
              run: npm run test-ci


